services:
  jenkins: 
    image: jenkins/jenkins:lts 
    container_name: jenkins 
    user: root 
    ports: 
      - "8088:8080" 
      - "50000:50000" 
    volumes: 
      - ./jenkins/jenkins_home:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./pdf_editor:/pdf_editor
    restart: unless-stopped