

services:
  mariadb:
    image: mariadb:lts
    container_name: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./maridadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pararas
      - MYSQL_PASSWORD=pararas
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud-php:
    image: nextcloud:stable-fpm
    container_name: nextcloud
    restart: always
    links:
      - mariadb
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=pararas
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mariadb

  apache:
    image: httpd:2.4-alpine
    container_name: apache
    restart: always
    ports:
      - 8080:80
    links:
      - nextcloud-php
    volumes:
      - ./apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./nextcloud:/var/www/html
    volumes_from:
      - nextcloud-php
    depends_on:
      - nextcloud-php

  iobroker:
    image: buanet/iobroker:latest-v9
    container_name: iobroker
    hostname: iobroker
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./iobroker:/opt/iobroker

  influxdb:
    image: influxdb:2
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=tino
      - DOCKER_INFLUXDB_INIT_PASSWORD=Avenge-Daycare0-Jury
      - DOCKER_INFLUXDB_INIT_ORG=tino
      - DOCKER_INFLUXDB_INIT_BUCKET=smarthome

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./grafana:/var/lib/grafana
