

services:
  mariadb:
    image: mariadb:10.3.39
    container_name: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /mnt/drive1/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=0rPYdrJfKyDW11Zzf7XDb5JxIaUKVk
      - MYSQL_PASSWORD=0rPYdrJfKyDW11Zzf7XDb5JxIaUKVk
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=oc_ncadmin
      - MARIADB_AUTO_UPGRADE=1

  nextcloud:
    image: nextcloud:stable-fpm
    container_name: nextcloud
    restart: always
    links:
      - mariadb
    volumes:
      - ./nextcloud:/var/www/html
      - /mnt/drive1/nc_data:/nc_data
    environment:
      - NEXTCLOUD_ADMIN_USER=ncadmin
      - NEXTCLOUD_ADMIN_PASSWORD=pmabSG3YUTYqCGaFBA6B
      - NEXTCLOUD_TRUSTED_DOMAINS=192.168.178.55 tinocloud.de
      - NEXTCLOUD_DATA_DIR=/nc_data
      - MYSQL_PASSWORD=0rPYdrJfKyDW11Zzf7XDb5JxIaUKVk
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=oc_ncadmin
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=1024M
    depends_on:
      - mariadb
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  apache:
    image: httpd:2.4-alpine
    container_name: apache
    restart: always
    ports:
      - 8080:80
      - 9090:90
    links:
      - nextcloud
      - grafana
    volumes:
      - ./apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nextcloud:/var/www/html
    volumes_from:
      - nextcloud
    depends_on:
      - nextcloud
    
  certbot-tinocloud:
    image: certbot/certbot
    container_name: certbot-tinocloud
    restart: always
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --keep-until-expiring --email davidjer@hotmail.de -d tinocloud.de --agree-tos --non-interactive

  certbot-grafana:
    image: certbot/certbot
    container_name: certbot-grafana
    restart: always
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --keep-until-expiring --email davidjer@hotmail.de -d grafana.tinocloud.de --agree-tos --non-interactive

  iobroker:
    image: buanet/iobroker:latest-v7
    container_name: iobroker
    hostname: iobroker
    restart: always
    ports:
      - 8081:8081
      - 502:502
      - 1883:1883
    volumes:
      - ./iobroker:/opt/iobroker

  influxdb:
    image: influxdb:2
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - /mnt/drive1/influxdb:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=tino
      - DOCKER_INFLUXDB_INIT_PASSWORD=Avenge-Daycare0-Jury
      - DOCKER_INFLUXDB_INIT_ORG=tino
      - DOCKER_INFLUXDB_INIT_BUCKET=smarthome

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./grafana/var:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_LOG_LEVEL=warn
    links:
      - influxdb
    depends_on:
      - influxdb
