volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:lts
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pararas
      - MYSQL_PASSWORD=pararas
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud-php:
    image: nextcloud:stable-fpm
    restart: always
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=pararas
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

  apache:
    image: httpd:2.4-alpine
    restart: always
    ports:
      - 8080:80
    links:
      - nextcloud-php
    volumes:
      - ./apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - nextcloud:/var/www/html
    volumes_from:
      - nextcloud-php
    depends_on:
      - nextcloud-php


