<?php
$CONFIG = array (
  'instanceid' => 'ocf7un6w7z5t',
  'passwordsalt' => 'zkzgbrxDmIdWqdUXA7bGbEojNd7N9g',
  'secret' => 'Dl03yNqtyJhUaPsHkmy76gehgv4O9yKm1yB2K6BVBkcJDeSz',
  'trusted_domains' => 
  array (
    0 => 'tinocloud.org',
    1 => '192.168.178.55',
  ),
  'datadirectory' => '/nc_data',
  'dbtype' => 'mysql',
  'version' => '30.0.8.1',
  'overwrite.cli.url' => 'http://ubuntu',
  'dbname' => 'nextcloud',
  'dbhost' => 'mariadb:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'oc_ncadmin',
  'dbpassword' => '0rPYdrJfKyDW11Zzf7XDb5JxIaUKVk',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'redis' => 
  array (
    'host' => 'redis',
    'port' => 6379,
  ),
  'default_phone_region' => 'GB',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'mail_from_address' => 'tinocloud.cloudns',
  'mail_domain' => 'gmail.com',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'tinocloud.cloudns@gmail.com',
  'mail_smtppassword' => 'iujtlwdtqvlyphpu',
  'mail_smtpsecure' => 'ssl',
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpport' => '465',
  'maintenance_window_start' => 3,
);
